import { expect, test } from '@playwright/test'

test('critical mobile journey: auth, navigation, programs, workout, and history', async ({ page }) => {
  const suffix = `${Date.now()}-${process.pid}`
  const email = `e2e-${suffix}@example.test`
  const password = 'RepLog-e2e-password-123'

  await page.goto('/')
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('link', { name: 'Register' }).first()).toBeVisible()
  await expect(page.getByRole('link', { name: 'Forgot password?' })).toBeVisible()

  await page.getByRole('link', { name: 'Register' }).first().click()
  await expect(page).toHaveURL(/\/register$/)
  await page.getByLabel('Username').fill(`e2euser${suffix.replace(/\D/g, '').slice(-10)}`)
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill(password)
  await page.getByRole('button', { name: /Create Account/ }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await expect(page.getByRole('heading', { name: 'Dashboard' })).toBeVisible()

  const primaryNav = page.getByRole('navigation', { name: 'Primary' })
  await expect(primaryNav).toBeVisible()
  await expect(primaryNav.getByRole('link', { name: 'Home' })).toHaveAttribute('aria-current', 'page')
  await primaryNav.getByRole('link', { name: 'History' }).click()
  await expect(page).toHaveURL(/\/history$/)
  await expect(page.getByRole('heading', { name: 'Workout History' })).toBeVisible()
  await primaryNav.getByRole('link', { name: 'Progress' }).click()
  await expect(page).toHaveURL(/\/progress$/)
  await primaryNav.getByRole('link', { name: 'Profile' }).click()
  await expect(page).toHaveURL(/\/profile$/)
  await primaryNav.getByRole('link', { name: 'Home' }).click()

  await page.goto('/program')
  await expect(page.getByRole('heading', { name: 'Programs' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Beginner Full Body' })).toBeVisible()
  await page.getByRole('button', { name: '+ New Program' }).click()
  const dialog = page.getByRole('dialog', { name: 'Try another program' })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Upper / Lower' }).click()
  await dialog.getByLabel('Program name').fill(`E2E Upper Lower ${suffix}`)
  await dialog.getByRole('button', { name: 'Create program' }).click()
  await expect(page).toHaveURL(/\/program\//)
  await page.getByRole('link', { name: 'Back to programs' }).click()
  const createdProgram = page.locator('article').filter({ has: page.getByRole('heading', { name: `E2E Upper Lower ${suffix}` }) })
  await expect(createdProgram).toBeVisible()
  await createdProgram.getByRole('button', { name: 'Make active' }).click()
  await expect(createdProgram.getByText('Active')).toBeVisible()

  await page.getByRole('link', { name: 'Home' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await page.getByRole('button', { name: 'Start Workout' }).click()
  await expect(page).toHaveURL(/\/workout\//)
  await expect(page.getByText('Active workout')).toBeVisible()

  const exercise = page.locator('article').filter({ has: page.getByRole('button', { name: 'Add Set' }) }).first()
  await exercise.getByRole('button', { name: 'Add Set' }).click()
  await exercise.getByLabel('Weight kg').fill('40')
  await exercise.getByLabel('Reps').fill('8')
  await exercise.getByRole('button', { name: 'Save Set' }).click()
  await expect(exercise.getByText('1 sets logged')).toBeVisible()
  await page.getByRole('button', { name: 'Finish Workout' }).click()
  await expect(page.getByText('Completed workout', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Finish Workout' })).toHaveCount(0)

  await page.getByRole('link', { name: 'History' }).click()
  await expect(page.getByRole('heading', { name: 'Workout History' })).toBeVisible()
  const historyEntry = page.locator('a').filter({ hasText: '1 sets' }).first()
  await expect(historyEntry).toBeVisible()
  await historyEntry.click()
  await expect(page).toHaveURL(/\/workout\/.*from=history/)
  await expect(page.getByText('Completed workout', { exact: true })).toBeVisible()
  await expect(page.getByText('40 kg')).toBeVisible()

  await page.goto('/dashboard')
  await page.getByRole('button', { name: 'Logout' }).click()
  await expect(page).toHaveURL(/\/login$/)
  await page.goto('/history')
  await expect(page).toHaveURL(/\/login$/)
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: /Login/ }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
})
